<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add raw.nyt_snapshot, drop the raw.ingest_heartbeat scaffolding (#6)';
    }

    public function up(Schema $schema): void
    {
        // In `raw`, created by the `symfony` role — that is what makes the
        // ALTER DEFAULT PRIVILEGES in db/init/02-schemas.sql grant `analytics`
        // read access without a second grant being remembered later.
        $this->addSql(<<<'SQL'
            CREATE TABLE raw.nyt_snapshot (
                id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                run_id         BIGINT NOT NULL,
                list_name      VARCHAR(64) NOT NULL,
                rank           SMALLINT NOT NULL,
                rank_last_week SMALLINT NOT NULL,
                isbn13         VARCHAR(13) NOT NULL,
                title          TEXT NOT NULL,
                author         TEXT NOT NULL,
                weeks_on_list  SMALLINT NOT NULL,
                published_date DATE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        // The run that wrote the row, so "what did this crawl cover" is a join
        // rather than a guess from timestamps. No cascade: runs are the audit
        // trail and are never deleted.
        $this->addSql(<<<'SQL'
            ALTER TABLE raw.nyt_snapshot
                ADD CONSTRAINT fk_nyt_snapshot_run FOREIGN KEY (run_id) REFERENCES raw.ingestion_run (id)
        SQL);

        // What makes re-crawling a week idempotent: the same book on the same list
        // for the same published_date is one row, upserted. Keyed on isbn13 rather
        // than rank because NYT ties ranks, and because primary_isbn13 is populated
        // on every row (see db/README.md).
        $this->addSql('CREATE UNIQUE INDEX uniq_nyt_snapshot_entry ON raw.nyt_snapshot (list_name, published_date, isbn13)');

        // #6's backfill asks "which weeks do I already have"; #12/#17 read a book's
        // rank over time. Both walk this index.
        $this->addSql('CREATE INDEX idx_nyt_snapshot_isbn_published ON raw.nyt_snapshot (isbn13, published_date)');

        // The scaffolding that proved the seam works (#3) has a real RAW table to
        // stand in for now. mart.hello_world goes with it, but `analytics` owns
        // `mart` and `symfony` cannot drop it — see analytics/README.md.
        $this->addSql('DROP TABLE IF EXISTS raw.ingest_heartbeat');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE raw.nyt_snapshot');

        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS raw.ingest_heartbeat (
                id          SERIAL PRIMARY KEY,
                source      VARCHAR(64) NOT NULL,
                observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        SQL);
    }
}
