<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260821120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add raw.ingestion_run';
    }

    public function up(Schema $schema): void
    {
        // In `raw`, and created by the `symfony` role: that is what makes the
        // ALTER DEFAULT PRIVILEGES in db/init/02-schemas.sql grant `analytics`
        // read access, so the Python side can chart coverage without a second
        // grant being remembered later.
        $this->addSql(<<<'SQL'
            CREATE TABLE raw.ingestion_run (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                source       VARCHAR(32) NOT NULL,
                status       VARCHAR(16) NOT NULL,
                started_at   TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                finished_at  TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                rows_written INT DEFAULT 0 NOT NULL,
                window_start DATE DEFAULT NULL,
                window_end   DATE DEFAULT NULL,
                error_class  VARCHAR(255) DEFAULT NULL,
                error        TEXT DEFAULT NULL,
                details      JSONB NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        // Every read is "the last N", for one source or for all of them.
        $this->addSql('CREATE INDEX idx_ingestion_run_source_started ON raw.ingestion_run (source, started_at)');

        // Predicate spelled the way pg_indexes.indexdef reports it back, not the
        // way it reads best: the schema comparator matches it literally.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_ingestion_run_active
                ON raw.ingestion_run (source, window_start, window_end)
                WHERE ((status)::text = 'running'::text)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE raw.ingestion_run');
    }
}
